// src/types/index.ts - canonical Atlas domain types.

// ---------- Branded ID types ----------

/** Stable project id - slug derived from hashing the absolute path. */
export type ProjectId = string;
/** Collection id - slug or uuid. */
export type CollectionId = string;
/** Todo id - uuid. */
export type TodoId = string;
/** Note id - uuid. */
export type NoteId = string;
/** Script id - uuid or deterministic key (e.g. "dev"). */
export type ScriptId = string;
/** Claude-Code session id - uuid, sourced from ~/.claude. */
export type SessionId = string;
/** Template id - slug ("node-ts") or uuid for user templates. */
export type TemplateId = string;
/** Terminal pane id - uuid assigned by the Rust PTY manager. */
export type PaneId = string;
/** Milestone id - uuid. */
export type MilestoneId = string;
/** Routine id - uuid. */
export type RoutineId = string;
/** Routine instance id - uuid. */
export type RoutineInstanceId = string;

// ---------- Enums ----------

export type Lang =
  | 'TypeScript'
  | 'JavaScript'
  | 'Rust'
  | 'Go'
  | 'Python'
  | 'Swift'
  | 'Kotlin'
  | 'Ruby'
  | 'Java'
  | 'C'
  | 'C++'
  | 'Other';

export type PaneKind = 'shell' | 'script' | 'claude-session';
export type PaneStatus = 'idle' | 'running' | 'active' | 'error';

export type SessionStatus = 'active' | 'idle' | 'archived';
export type FileKind = 'dir' | 'file';
export type FileStatus = 'M' | '+' | '-' | null;
export type ScriptGroup = 'run' | 'build' | 'check' | 'util';
export type Theme = 'dark' | 'light' | 'system';
export type GitPollInterval = '10s' | '30s' | '1m' | 'off';
export type CloneDepth = number | 'full';

// ---------- Core entities ----------

export interface Project {
  id: ProjectId;
  name: string;
  /** Absolute path on disk. */
  path: string;
  language: Lang;
  /** Hex color; defaults derived from language. */
  color: string;
  branch: string;
  /** Uncommitted file count. */
  dirty: number;
  ahead: number;
  behind: number;
  // Last-commit author name. `null` until the git refresh populates it
  author?: string | null;
  /** Cached LOC (periodic tokei scan). */
  loc: number;
  /** Pretty-printed source size (e.g. "412 MB"). Respects .gitignore. */
  size: string;
  sizeBytes: number;
  /** Pretty-printed on-disk size (e.g. "16.4 GB"). Full tree, no .gitignore. */
  diskSize: string;
  /** Full on-disk footprint in bytes. Always >= sizeBytes. */
  diskBytes: number;
  /** ISO-8601 timestamp, or null if never opened. */
  lastOpened: string | null;
  pinned: boolean;
  tags: string[];
  todosCount: number;
  notesCount: number;
  /** Tracked time, pretty-printed (e.g. "12h 08m"). */
  time: string;
  archived: boolean;
  collectionIds: CollectionId[];
}

export interface Collection {
  id: CollectionId;
  label: string;
  /** Hex or OKLCH color for the sidebar dot. */
  dot: string;
  order: number;
}

export interface Todo {
  id: TodoId;
  done: boolean;
  text: string;
  /** Legacy free-form due label ("today", "fri", ISO-8601). Preserved
   *  for backward compatibility; new writes prefer `deadline`. */
  due?: string;
  /** ISO-8601. */
  createdAt: string;

  // ---- Planner-feature fields (P1 schema; populated by P2+ flows) ----

  /** Owning project id. Optional during the migration window. */
  projectId?: ProjectId;
  /** Membership in a project milestone. */
  milestoneId?: MilestoneId;
  /** Set when this todo was generated by a routine instance. */
  routineInstanceId?: RoutineInstanceId;
  /** Importance bucket. Defaults to `'p2'` when absent. */
  priority?: Priority;
  /** Structured ISO-8601 deadline. Replaces free-form `due` in new writes. */
  deadline?: string;
  /** Estimated minutes-of-work (for the workload bar). */
  estimate?: number;
  /** User explicitly pinned this todo into Today, overriding scoring. */
  pinnedToday?: boolean;
  /** ISO-8601 completion timestamp. */
  doneAt?: string;
}

export interface Note {
  id: NoteId;
  title: string;
  /** Tiptap-serialized HTML. */
  body: string;
  pinned: boolean;
  /** ISO-8601. */
  createdAt: string;
  /** ISO-8601. */
  updatedAt: string;
}

export interface ScriptEnvVar {
  key: string;
  default: string;
}

export interface Script {
  id: ScriptId;
  name: string;
  cmd: string;
  desc?: string;
  group: ScriptGroup;
  default?: boolean;
  icon?: string;
  /** Env vars the user defined alongside this script. Defaults are
   * applied automatically on plain "run"; the run-env modal lets the
   * user override them per-invocation before launch. */
  env_defaults?: ScriptEnvVar[];
}

export interface Session {
  id: SessionId;
  /** Provider id (`"claude"` | `"codex"` | `"opencode"` | …). */
  provider: string;
  projectPath: string;
  title: string;
  /** ISO-8601. */
  when: string;
  turns: number;
  /** Pretty-printed ("47m"). */
  duration: string;
  status: SessionStatus;
  /** Snippet of the last user/assistant line. */
  last: string;
  model: string;
  branch?: string;
}

export interface FileNode {
  depth: number;
  name: string;
  path: string;
  kind: FileKind;
  status?: FileStatus;
  /** e.g. "+42 -18". */
  delta?: string;
}

export interface Template {
  id: TemplateId;
  label: string;
  color: string;
  hint: string;
  path: string;
  builtin: boolean;
}

/** One `{{key}}` placeholder declared on a launch template. */
export interface LaunchTemplateVar {
  key: string;
  label: string;
  default: string;
  hint: string;
  multiline: boolean;
  /** Non-empty => the wizard renders a `<select>` instead of a text input. */
  options: string[];
  required: boolean;
}

/** Template for starting a new Claude Code session with a pre-filled prompt. */
export interface LaunchTemplate {
  id: string;
  label: string;
  hint: string;
  color: string;
  /** Tiptap-serialized HTML (same format as Note.body). */
  body: string;
  variables: LaunchTemplateVar[];
  createdAt: string;
  updatedAt: string;
}

/** One Claude Code skill discovered on disk (hand-mirror of rust.ts). */
export interface ClaudeSkill {
  /** Invocation name: dir name, or `plugin:dir` for plugin skills. */
  name: string;
  /** Frontmatter description, "" if absent. */
  description: string;
  /** "user" | "project" | "plugin". */
  scope: string;
  /** Plugin name for plugin-scoped skills, null otherwise. */
  plugin: string | null;
  /** Absolute skill directory path. */
  path: string;
}

export interface Pane {
  id: PaneId;
  kind: PaneKind;
  title: string;
  status: PaneStatus;
  cwd: string;
  branch?: string;
  scriptId?: ScriptId;
  sessionId?: SessionId;
  // Owning project id (optional - legacy panes without one are treated as
  projectId?: ProjectId;
  // Human-readable project label (name, not path). Stored on the pane
  projectLabel?: string;
  // Command + args the pane was spawned with. Set for `script` panes
  command?: string;
  args?: string[];
}


// Subset of `Pane` that can be serialized between runs. Live PTY
export interface PaneSnapshot {
  id: string;
  // One of `PaneKind` values; stored as a string so unknown kinds on
  kind: string;
  title: string;
  cwd: string;
  scriptId?: ScriptId;
  sessionId?: SessionId;
}

// Last-known layout for a project's terminal strip. Persisted at
export interface PaneLayout {
  // One of `'tabs' | 'split-v' | 'split-h' | 'grid'`; kept as string
  mode: string;
  panes: PaneSnapshot[];
  activePaneId?: string;
}

// Body for `templates.create_project`. Fields are all explicit so the
export interface CreateProjectParams {
  name: string;
  // Absolute path to the parent directory. Must be inside $HOME (or a
  parent: string;
  templateId: TemplateId;
  initGit: boolean;
  createEnv: boolean;
  /** Optional editor id; the caller is responsible for launching. */
  openInEditor?: string;
}

// ---------- Settings ----------

export interface EditorEntry {
  id: string;
  name: string;
  cmd: string;
  present: boolean;
}

export interface WatchRoot {
  path: string;
  depth: number;
  repoCount: number;
}


// Result of `projects.discover(root, depth?)` - returned so the UI can
export interface DiscoveryResult {
  root: string;
  newProjectIds: ProjectId[];
  totalRepos: number;
}

// Partial `Project` patch used by streaming `project:updated` events and
export type ProjectPatch = Partial<Project> & { id: ProjectId };

// IPC-facing shape for `settings.watchers.list` / `.add`. Mirrors the
export interface WatchRootDto {
  path: string;
  depth: number;
  repoCount: number;
}

export interface GeneralSettings {
  launchAtLogin: boolean;
  menuBarAgent: boolean;
  defaultProjectLocation: string;
  theme: Theme;
  terminalTheme: Theme;
}

export interface EditorsSettings {
  detected: EditorEntry[];
  defaultId: string | null;
}

export interface GitSettings {
  pollInterval: GitPollInterval;
  showAuthor: boolean;
  defaultCloneDepth: CloneDepth;
  sshKey: string;
}

export interface AdvancedSettings {
  useSpotlight: boolean;
  crashReports: boolean;
  shell: string;
  crashLog: boolean;
  mcp: McpSettings;
  agent: AgentSettings;
}

export interface McpSettings {
  enabled: boolean;
  port: number;
  /** Bearer token clients send in `Authorization: Bearer …`. Empty = server refuses to start. */
  token: string;
}

export interface AgentSettings {
  enabled: boolean;
  /** WebSocket URL of the relay (defaults to local stub `ws://localhost:9000/agent`). */
  relayUrl: string;
  /** Bearer token presented on the WS upgrade. Separate from the device's signing key. */
  token: string;
}

export interface PairingInfo {
  /** Short, displayable fingerprint (first 8 bytes of pubkey, hex). */
  deviceId: string;
  /** Full ed25519 public key, hex-encoded (64 chars). */
  publicKey: string;
  /** Default relay URL — what the QR code suggests to the mobile app. */
  defaultRelayUrl: string;
}

export interface PairEnvelope {
  /** Where the mobile should POST the envelope (`<relay_base>/pair`). */
  relayBaseUrl: string;
  /** JSON string of the signed pair envelope. Mobile sends verbatim. */
  envelopeJson: string;
  /** Convenience copy of the device id for UI display. */
  deviceId: string;
}

export interface ProvidersSettings {
  /** Per-provider enable flag. Missing entries default to `true`. */
  enabled: Record<string, boolean>;
  /** Provider id used by the "+ new session" main click. */
  defaultId: string;
}

export interface Settings {
  general: GeneralSettings;
  editors: EditorsSettings;
  git: GitSettings;
  watchers: WatchRoot[];
  templates: Template[];
  shortcuts: Record<string, string>;
  advanced: AdvancedSettings;
  providers: ProvidersSettings;
}


// Discriminated union returned by `palette.query(query, limit?)`.
export type PaletteItem =
  | { kind: 'project'; project: Project; score: number }
  | { kind: 'recent'; project: Project }
  | {
      kind: 'note';
      projectId: ProjectId;
      noteId: NoteId;
      title: string;
      snippet: string;
      score: number;
    }
  | { kind: 'action'; id: string; label: string; hint: string; keys: string[] };

// =============================================================
// Planner feature — milestones, routines, scoring, timeline.
// Schema introduced 2026-04-30. All Todo additions are optional
// to keep existing files loadable.
// =============================================================

/** Importance bucket. Drives the scoring weights in score_engine
 *  (P0=2× / P1=1.5× / P2=1× / P3=0.5×). */
export type Priority = 'p0' | 'p1' | 'p2' | 'p3';

/** Lifecycle of a milestone. */
export type MilestoneStatus =
  | 'planned'
  | 'active'
  | 'done'
  | 'missed'
  | 'cancelled';

/** Why a deadline was extended. Determines whether akrasia-horizon cost
 *  applies. */
export type ExtensionReason =
  | 'auto-missed'
  | 'user-soften'
  | 'user-override'
  | 'paused';

/** One entry in a milestone or routine's `extensions` log. Same shape
 *  for both because the surfaces are identical. */
export interface ExtensionEvent {
  /** ISO-8601 — date being moved away from. */
  from: string;
  /** ISO-8601 — new target date. */
  to: string;
  reason: ExtensionReason;
  failingPointsApplied: number;
  /** ISO-8601 — when the extension was recorded. */
  at: string;
  /** Optional free-form note ("scope grew", "external dep slipped"). */
  note?: string;
}

/** Goal definition attached to a routine. Discriminated on `kind`. */
export type Goal =
  | { kind: 'count'; target: number; completed: number }
  | { kind: 'deadline'; until: string }
  | { kind: 'indefinite' };

export interface Milestone {
  id: MilestoneId;
  projectId: ProjectId;
  title: string;
  description?: string;
  /** ISO-8601 — current target date. */
  deadline: string;
  /** ISO-8601 — first-set target. Immutable after first save. */
  originalDeadline: string;
  status: MilestoneStatus;
  priority: Priority;
  order: number;
  todoIds: TodoId[];
  extensions: ExtensionEvent[];
  successPoints: number;
  failingPoints: number;
  createdAt: string;
  doneAt?: string;
}

export interface Routine {
  id: RoutineId;
  /** Optional — `undefined` means a global routine spanning all projects. */
  projectId?: ProjectId;
  title: string;
  description?: string;
  /** RFC 5545 RRULE without the `RRULE:` prefix. */
  rrule: string;
  /** ISO-8601 date the recurrence anchors on. */
  startDate: string;
  goal: Goal;
  priority: Priority;
  /** Estimated minutes per instance. */
  estimate?: number;
  paused: boolean;
  /** ISO-8601 timestamp the pause began. */
  pausedFrom?: string;
  successPoints: number;
  failingPoints: number;
  extensions: ExtensionEvent[];
  createdAt: string;
}

export interface RoutineInstance {
  id: RoutineInstanceId;
  routineId: RoutineId;
  /** ISO-8601 date the instance is due (strict / calendar-anchored). */
  scheduledFor: string;
  doneAt?: string;
  skipped?: boolean;
  /** Days added to the routine's projected goal-completion when missed. */
  extensionContribution: number;
  failingPoints: number;
  successPoints: number;
}

export interface TimelineConfig {
  /** User-pinned projects. Order matters (renders top-to-bottom). */
  pinnedProjectIds: ProjectId[];
  /** Default visible range — `'week'` or `'month'`. */
  visibleRange: 'week' | 'month';
}

export interface ScoreSnapshot {
  /** ISO-8601 date the snapshot represents. */
  date: string;
  successPoints: number;
  failingPoints: number;
  /** successPoints / (successPoints + failingPoints), or 1.0 if both 0. */
  successRate: number;
}

export interface PlannerState {
  /** Pause-all is the vacation safety valve. While true, no new failing
   *  points accrue across any routine or milestone. */
  pausedAll: boolean;
  /** ISO-8601 — when paused_all flipped on. */
  pausedFrom?: string;
  /** ISO-8601 — last time the headline notification fired. */
  lastNotificationAt?: string;
  /** `YYYY-MM-DD` (local) — last day the session-start notification fired. */
  lastSessionDate?: string;
  scoreSnapshots: ScoreSnapshot[];
}

// ---- Today view DTOs (mirrors commands/planner.rs) ----

export type TodayItem =
  | {
      kind: 'todo';
      id: string;
      projectId: ProjectId;
      projectName: string;
      text: string;
      priority: Priority;
      deadline: string | null;
      score: number;
      daysOverdue: number;
      pinnedToday: boolean;
    }
  | {
      kind: 'milestone-deadline';
      id: MilestoneId;
      projectId: ProjectId;
      projectName: string;
      title: string;
      deadline: string;
      priority: Priority;
      score: number;
    }
  | {
      kind: 'routine-instance';
      id: string;
      routineId: RoutineId;
      projectId: ProjectId | null;
      projectName: string | null;
      title: string;
      scheduledFor: string;
      priority: Priority;
      score: number;
    };

export interface SoonestMilestoneRef {
  id: MilestoneId;
  projectId: ProjectId;
  projectName: string;
  title: string;
  deadline: string;
  priority: Priority;
  daysLeft: number;
}

export interface PlannerToday {
  mustDo: TodayItem[];
  couldDo: TodayItem[];
  topPriority: TodayItem | null;
  deadlinesTomorrow: TodayItem[];
  /** Sum of estimates across must-do items, in minutes. */
  totalEstimateMinutes: number;
  pausedAll: boolean;
  /** Active milestone whose deadline is closest, across all projects. */
  soonestMilestone: SoonestMilestoneRef | null;
  /** Open todos belonging to the soonest milestone — surfaced in Today
   *  even when they don't have their own deadline. */
  soonestMilestoneTodos: TodayItem[];
}

export interface ScoreSummary {
  lifetime: ScoreSnapshot;
  rolling30d: ScoreSnapshot;
  daily: ScoreSnapshot[];
}

export interface SessionStartResult {
  fired: boolean;
  localDate: string;
  today: PlannerToday | null;
}

// ---- Timeline DTOs (mirrors commands/timeline.rs) ----

export interface TimelineRow {
  projectId: ProjectId;
  projectName: string;
  /** Hex color of the project. */
  projectColor: string;
  milestones: Milestone[];
  routines: Routine[];
  routineInstances: RoutineInstance[];
}

export interface TimelineData {
  config: TimelineConfig;
  rows: TimelineRow[];
  /** `YYYY-MM-DD`. */
  start: string;
  end: string;
  today: string;
}
