// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentSettings = { enabled: boolean, 
/**
 * WebSocket URL of the relay. Default points at the local stub for
 * dev (`ws://localhost:9000/agent`). Production relay URL ships
 * later; users can override per-device.
 */
relayUrl: string, 
/**
 * Bearer token presented to the relay on the WS upgrade. Separate
 * from the device's signing key — the token authenticates the
 * connection at the transport layer; signed envelopes authenticate
 * individual messages.
 */
token: string, };
