// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdvancedSettings = { useSpotlight: boolean, crashReports: boolean, shell: string, 
/**
 * hook appends each panic payload + backtrace to
 */
crashLog: boolean, 
/**
 * Embedded MCP server config (remote-control feature). Default-off,
 * loopback-only; the user opts in from Settings → Advanced.
 */
mcp: McpSettings, 
/**
 * Outbound agent that connects to the relay backend (remote-control
 * feature). Default-off; settings here are only used if no
 * `ATLAS_AGENT_*` env vars are set (env wins for dev override).
 */
agent: AgentSettings, };

export type AgentSettings = { enabled: boolean, 
/**
 * WebSocket URL of the relay. Default points at the local stub for
 * dev (`ws://localhost:9000/agent`). Production relay URL ships
 * later; users can override per-device.
 */
relayUrl: string, 
/**
 * Bearer token presented to the relay on the WS upgrade. Separate
 * from the device's signing key — the token authenticates the
 * connection at the transport layer; signed envelopes authenticate
 * individual messages.
 */
token: string, };

/**
 * A single row returned by `git_branch_list`.
 */
export type BranchInfo = { 
/**
 * Short branch name, e.g. `main` or `origin/feat/x`.
 */
name: string, 
/**
 * True when this branch is the current HEAD (only meaningful for local
 */
isHead: boolean, 
/**
 * True for remote-tracking branches (`refs/remotes/...`).
 */
isRemote: boolean, };

/**
 * One conversational message extracted from a session transcript.
 */
export type ChatMessage = { 
/**
 * `"user"` or `"assistant"`.
 */
role: string, text: string, };

/**
 * One installed Claude Code skill (user, project, or plugin scope).
 */
export type ClaudeSkill = { 
/**
 * Invocation name: the skill's directory name, or `plugin:dir` for
 * plugin skills. (The frontmatter `name:` is display-only.)
 */
name: string, 
/**
 * Frontmatter `description:`, `""` when absent.
 */
description: string, 
/**
 * `"user"` | `"project"` | `"plugin"`.
 */
scope: string, 
/**
 * `Some(plugin name)` for plugin skills.
 */
plugin: string | null, 
/**
 * Absolute path of the skill directory.
 */
path: string, };

/**
 * Clone depth - `number | 'full'` in TS. Encoded here as a tagged enum
 */
export type CloneDepth = number | FullLiteral;

export type Collection = { id: string, label: string, dot: string, order: number, };

/**
 * Request body for creating a new project from a template.
 */
export type CreateProjectParams = { 
/**
 * Display name for the new project. Also used as the directory
 */
name: string, 
/**
 * Absolute path to the parent directory that will hold the new
 */
parent: string, 
/**
 * Template id; matched against built-ins first, then user templates.
 */
templateId: string, 
/**
 * If true, run `git init` inside the new folder.
 */
initGit: boolean, 
/**
 * If true, create an empty `.env` with a single comment line.
 */
createEnv: boolean, 
/**
 * Optional editor id to open the new project in. Resolution + launch
 */
openInEditor: string | null, };

/**
 * Result of `Db::discover_root` - returned to UI so it can surface a
 */
export type DiscoveryResult = { root: string, newProjectIds: Array<string>, totalRepos: number, };

/**
 * Row returned by `disk.scan`. Shape matches the `DiskEntry` interface
 */
export type DiskEntry = { 
/**
 * Human-readable label - the top-level dir name, or `(files)` for
 */
label: string, 
/**
 * Absolute path on disk (for the Reveal-in-Finder action).
 */
path: string, bytes: number, 
/**
 * Pretty-printed size, e.g. "412 MB".
 */
size: string, 
/**
 * 0..1 share of the total.
 */
pct: number, 
/**
 * True when `label` matches a well-known regeneratable directory
 */
cleanable: boolean, };

/**
 * Aggregate shape returned by `disk.scan`. Matches
 */
export type DiskScanResult = { totalBytes: number, totalSize: string, entries: Array<DiskEntry>, };

export type EditorEntry = { id: string, name: string, cmd: string, present: boolean, };

export type EditorsSettings = { detected: Array<EditorEntry>, defaultId: string | null, };

/**
 * `.atlas/pilot/epics/NN.json` — one epic. The skill writes it at the
 * epics gate; Atlas mutates `status`, `session_id`, `iterations`,
 * `tasks[].done` thereafter.
 */
export type Epic = { number: number, title: string, goal: string, description: string, 
/**
 * Release group id; epics sharing one run in a single session.
 */
release: string | null, status: EpicStatus, 
/**
 * Epic numbers this epic depends on.
 */
dependsOn: number[], tasks: Array<EpicTask>, 
/**
 * Claude session id implementing this epic, once spawned.
 */
sessionId: string | null, 
/**
 * Task-checkpoint cycles run so far (one per `continue`).
 */
iterations: number, };

/**
 * Implementation status of a single epic.
 */
export type EpicStatus = "pending" | "active" | "interrupted" | "done";

/**
 * One task within an epic's task list.
 */
export type EpicTask = { id: string, title: string, done: boolean, };

/**
 * One entry in a Milestone or Routine's `extensions` log. The shape is
 * shared between both because the surfaces are identical.
 */
export type ExtensionEvent = { 
/**
 * ISO-8601 — date being moved away from.
 */
from: string, 
/**
 * ISO-8601 — new target date.
 */
to: string, reason: ExtensionReason, failingPointsApplied: number, 
/**
 * ISO-8601 — when the extension was recorded.
 */
at: string, 
/**
 * Optional free-form note ("scope grew", "external dep slipped").
 */
note: string | null, };

/**
 * Why a deadline was extended. Determines whether the akrasia-horizon
 * cost applies.
 */
export type ExtensionReason = "auto-missed" | "user-soften" | "user-override" | "paused";

/**
 * Diff payload used by the Inspector → Files tab when the user clicks a
 * changed file. We hand the renderer two raw strings and let the JS diff
 * viewer compute the visual diff.
 */
export type FileDiff = { 
/**
 * Path relative to the project root.
 */
path: string, 
/**
 * Status char, mirroring `git::FileStatus::status` (`M`/`+`/`-`).
 */
status: string, 
/**
 * File contents at HEAD. Empty string when the file is newly added.
 */
oldContent: string, 
/**
 * File contents in the working tree. Empty string when the file is
 * deleted.
 */
newContent: string, 
/**
 * True when either side looks binary (NUL byte in the first 8 KB).
 * The UI uses this to hide the diff viewer and show a fallback note.
 */
isBinary: boolean, };

export type FileKind = "dir" | "file";

export type FileNode = { depth: number, name: string, path: string, kind: FileKind, 
/**
 * `Some("M")` / `Some("+")` / `Some("-")` / `None`.
 */
status: string | null, delta: string | null, };

/**
 * Literal wrapper so `untagged` can distinguish "full" from a number.
 */
export type FullLiteral = "full";

export type GeneralSettings = { launchAtLogin: boolean, menuBarAgent: boolean, defaultProjectLocation: string, theme: Theme, terminalTheme: Theme, };

/**
 * Result of a mutating git action - surfaces the exit code and the raw
 */
export type GitActionResult = { ok: boolean, stdout: string, stderr: string, };

/**
 * Read-only result of a checkout preview.
 */
export type GitCheckoutPreview = { 
/**
 * The branch that was previewed (echoed from the request).
 */
branch: string, 
/**
 * Count of files whose blob differs between `HEAD` and the target
 */
filesWouldChange: number, 
/**
 * True when the working tree has uncommitted changes.
 */
isDirty: boolean, 
/**
 * Human-readable warning shown in the confirmation dialog. `Some`
 */
warning: string | null, };

export type GitPollInterval = "10s" | "30s" | "1m" | "off";

export type GitSettings = { pollInterval: GitPollInterval, showAuthor: boolean, defaultCloneDepth: CloneDepth, sshKey: string, };

/**
 * Goal definition attached to a Routine. The TypeScript shape is a
 * discriminated union on `kind`.
 */
export type Goal = { "kind": "count", target: number, 
/**
 * Running tally of completed instances. Maintained by the engine.
 */
completed: number, } | { "kind": "deadline", until: string, } | { "kind": "indefinite" };

/**
 * One line of `.atlas/pilot/epics/NN/history.jsonl`.
 */
export type HistoryEntry = { 
/**
 * ISO-8601 UTC timestamp.
 */
ts: string, kind: HistoryKind, summary: string, files: Array<string>, rationale: string, };

/**
 * Kind of a `history.jsonl` entry.
 */
export type HistoryKind = "task" | "mod" | "question" | "epic";

export type Lang = "TypeScript" | "JavaScript" | "Rust" | "Go" | "Python" | "Swift" | "Kotlin" | "Ruby" | "Java" | "C" | "C++" | "Other";

/**
 * Template for starting a new Claude Code session with a pre-filled prompt.
 */
export type LaunchTemplate = { id: string, label: string, hint: string, 
/**
 * Hex color, same convention as scaffold `Template.color`.
 */
color: string, 
/**
 * Tiptap-serialized HTML (same format as `Note.body`).
 */
body: string, variables: Array<LaunchTemplateVar>, 
/**
 * ISO-8601 rfc3339.
 */
createdAt: string, updatedAt: string, };

/**
 * One declared `{{key}}` placeholder in a launch template body.
 */
export type LaunchTemplateVar = { key: string, label: string, default: string, hint: string, multiline: boolean, 
/**
 * Non-empty => render as a `<select>`.
 */
options: Array<string>, required: boolean, };

export type McpSettings = { enabled: boolean, port: number, 
/**
 * Bearer token clients must send in `Authorization: Bearer …`.
 * Empty string means the server refuses to start (no anonymous access).
 */
token: string, };

/**
 * A milestone groups a set of todos under a single deadline within a
 * project.
 */
export type Milestone = { id: string, projectId: string, title: string, description: string | null, 
/**
 * ISO-8601 — current target date.
 */
deadline: string, 
/**
 * ISO-8601 — first-set target. Immutable after first save; what the
 * "extended to X instead of Y" warning anchors to.
 */
originalDeadline: string, status: MilestoneStatus, priority: Priority, order: number, 
/**
 * Ordered membership; todos retain their own ordering for display.
 */
todoIds: Array<string>, extensions: Array<ExtensionEvent>, 
/**
 * Running success points accrued from member todos.
 */
successPoints: number, 
/**
 * Running failing points accrued from late/missed todos and from
 * soften-extensions inside the akrasia horizon.
 */
failingPoints: number, createdAt: string, doneAt: string | null, };

/**
 * Lifecycle state of a Milestone.
 */
export type MilestoneStatus = "planned" | "active" | "done" | "missed" | "cancelled";

export type Note = { id: string, title: string, body: string, pinned: boolean, createdAt: string, updatedAt: string, };

export type PairEnvelope = { 
/**
 * Where the mobile should POST the envelope (`<relay_base>/pair`).
 * Derived from the agent settings — production deployments override
 * this from Settings → Atlas Agent.
 */
relayBaseUrl: string, 
/**
 * JSON string of the signed pair envelope. Mobile sends this
 * verbatim as the request body. Re-encoding would break the
 * signature (canonical-JSON byte equality matters).
 */
envelopeJson: string, 
/**
 * Convenience copy of the device id from inside the envelope, so
 * the UI can show it without re-parsing.
 */
deviceId: string, };

export type PairingInfo = { 
/**
 * Short, displayable fingerprint (first 8 bytes of pubkey, hex).
 */
deviceId: string, 
/**
 * Full ed25519 public key, hex-encoded (64 chars).
 */
publicKey: string, 
/**
 * Default relay URL — what the QR code suggests to the mobile app.
 */
defaultRelayUrl: string, };

export type PaletteItem = { "kind": "project", project: Project, score: number, } | { "kind": "recent", project: Project, } | { "kind": "note", projectId: string, noteId: string, title: string, snippet: string, score: number, } | { "kind": "milestone", projectId: string, projectName: string, milestoneId: string, title: string, deadline: string, priority: Priority, status: MilestoneStatus, score: number, } | { "kind": "routine", routineId: string, projectId: string | null, projectName: string | null, title: string, rrule: string, priority: Priority, score: number, } | { "kind": "action", id: string, label: string, hint: string, keys: Array<string>, };

export type Pane = { id: string, kind: PaneKind, title: string, status: PaneStatus, cwd: string, branch: string | null, scriptId: string | null, sessionId: string | null, };

export type PaneKind = "shell" | "script" | "claude-session";

/**
 * Last-known layout for a project's terminal strip. Persisted on every
 */
export type PaneLayout = { 
/**
 * One of "tabs" | "split-v" | "split-h" | "grid". Kept as string
 */
mode: string, panes: Array<PaneSnapshot>, activePaneId: string | null, };

/**
 * The snapshot we persist per pane. Carries the user-visible hints
 */
export type PaneSnapshot = { id: string, 
/**
 * One of "shell" | "script" | "claude-session" (mirrors `PaneKind`).
 */
kind: string, title: string, cwd: string, scriptId: string | null, sessionId: string | null, };

export type PaneStatus = "idle" | "running" | "active" | "error";

/**
 * Everything the Pilot window renders for one project.
 */
export type PilotDetail = { path: string, project: PilotProject, epics: Array<Epic>, 
/**
 * Whether a `claude` session is live for this project right now.
 */
running: boolean, 
/**
 * Whether that run is currently paused.
 */
paused: boolean, 
/**
 * PTY pane id of the live session — used to embed the terminal.
 */
paneId: string | null, };

/**
 * Which planning gate a draft pilot is currently waiting on.
 */
export type PilotGate = "reqs" | "prd" | "epics";

/**
 * `.atlas/pilot/project.json` — Atlas-owned pilot project record.
 */
export type PilotProject = { name: string, status: PilotStatus, 
/**
 * Current planning gate; `None` once `status` is `Active`/`Done`.
 */
gate: PilotGate | null, 
/**
 * Always true today (decision: auto-advance always). Kept as a field
 * so the orchestrator can read it without a special-case.
 */
autoAdvance: boolean, 
/**
 * Claude session id of the planning session, once spawned.
 */
planningSessionId: string | null, 
/**
 * ISO-8601 creation timestamp.
 */
createdAt: string, };

/**
 * Lifecycle status of a pilot project as a whole.
 */
export type PilotStatus = "draft" | "active" | "done";

/**
 * One row in the Pilot window's project list.
 */
export type PilotSummary = { path: string, name: string, status: PilotStatus, };

/**
 * Global planner state — pause flag, last notification bookkeeping,
 * rolling score snapshots.
 */
export type PlannerState = { 
/**
 * Pause-all is the vacation safety valve. While true, no new
 * failing points accrue across any routine or milestone.
 */
pausedAll: boolean, 
/**
 * ISO-8601 — when paused_all flipped on.
 */
pausedFrom: string | null, 
/**
 * ISO-8601 — last time the headline notification fired.
 */
lastNotificationAt: string | null, 
/**
 * `YYYY-MM-DD` (local) — last day the session-start notification
 * fired. Compared against today to enforce "once per day".
 */
lastSessionDate: string | null, scoreSnapshots: Array<ScoreSnapshot>, };

export type PlannerToday = { mustDo: Array<TodayItem>, couldDo: Array<TodayItem>, topPriority: TodayItem | null, deadlinesTomorrow: Array<TodayItem>, 
/**
 * Sum of estimates across must-do items, in minutes.
 */
totalEstimateMinutes: number, 
/**
 * True when the global pause-all flag is set; the UI uses this to
 * pulse a banner so the user remembers they paused.
 */
pausedAll: boolean, 
/**
 * The active milestone whose deadline is closest. None when no
 * active milestone exists across all projects.
 */
soonestMilestone: SoonestMilestoneRef | null, 
/**
 * Open todos belonging to `soonest_milestone`. Surfaces them in
 * Today regardless of whether they have their own deadline.
 */
soonestMilestoneTodos: Array<TodayItem>, };

/**
 * Importance bucket for todos, milestones, and routines. Drives the
 * scoring weights in `score_engine` (P0=2× / P1=1.5× / P2=1× / P3=0.5×).
 */
export type Priority = "p0" | "p1" | "p2" | "p3";

export type Project = { id: string, name: string, path: string, language: Lang, color: string, branch: string, dirty: number, ahead: number, behind: number, loc: number, size: string, sizeBytes: number, 
/**
 * Pretty-printed on-disk size, e.g. `"16.4 GB"`. Matches
 * `disk_bytes` formatting via `util::format_bytes`.
 */
diskSize: string, 
/**
 * Full on-disk footprint including files `.gitignore` hides
 * (`node_modules`, build outputs). Always ≥ `size_bytes`.
 */
diskBytes: number, lastOpened: string | null, pinned: boolean, tags: Array<string>, todosCount: number, notesCount: number, time: string, archived: boolean, collectionIds: Array<string>, 
/**
 * Author name of the repo's current HEAD commit, or `None` for
 */
author: string | null, };

/**
 * Camel-case DTO returned by `projects_refresh_metrics`.
 */
export type ProjectMetricsDto = { loc: number, sizeBytes: number, 
/**
 * Pretty-printed source size, e.g. `"412 MB"`.
 */
size: string, diskBytes: number, 
/**
 * Pretty-printed on-disk size, e.g. `"16.4 GB"`.
 */
diskSize: string, };

/**
 * Outcome of a single `projects.repair` invocation. camelCase in the TS
 */
export type ProjectRepairReport = { 
/**
 * Number of files re-read (present OR absent). `project.json`,
 */
filesChecked: number, 
/**
 * Subset of `files_checked` where the on-disk contents were
 */
filesRepaired: number, 
/**
 * Human-readable notes for each repaired / skipped file. Surfaced in
 */
issues: Array<string>, };

/**
 * What the Settings panel + Sessions tab need to know about a provider.
 */
export type ProviderInfo = { id: string, label: string, binaryName: string, 
/**
 * Binary discovered on PATH at the time of the call.
 */
available: boolean, 
/**
 * Reflects the user's setting (defaults to true when unset).
 */
enabled: boolean, 
/**
 * True when the user picked this as the default for "+ new session".
 */
isDefault: boolean, };

export type ProvidersSettings = { 
/**
 * Per-provider enable flag. Missing entries default to `true` so
 * newly-registered providers light up automatically.
 */
enabled: { [key in string]?: boolean }, 
/**
 * Provider id used by the "+ new session" main click.
 */
defaultId: string, };

/**
 * Argv + cwd a Tauri command should hand to the terminal pane / shell.
 */
export type ResumeInvocation = { provider: string, command: string, args: Array<string>, cwd: string, };

/**
 * A recurring task definition. Cadence is RFC 5545 RRULE; instances
 * are materialised to `RoutineInstance` records.
 */
export type Routine = { id: string, 
/**
 * Optional — `None` means a global routine spanning all projects.
 */
projectId: string | null, title: string, description: string | null, 
/**
 * RFC 5545 RRULE without the `RRULE:` prefix.
 */
rrule: string, 
/**
 * ISO-8601 date the recurrence anchors on.
 */
startDate: string, goal: Goal, priority: Priority, 
/**
 * Estimated minutes per instance (for workload bar).
 */
estimate: bigint | null, paused: boolean, 
/**
 * ISO-8601 timestamp the pause began.
 */
pausedFrom: string | null, successPoints: number, failingPoints: number, extensions: Array<ExtensionEvent>, createdAt: string, };

/**
 * One materialised occurrence of a Routine. Generated lazily by the
 * engine up to `MAX_HORIZON_DAYS` ahead.
 */
export type RoutineInstance = { id: string, routineId: string, 
/**
 * ISO-8601 date the instance is due (strict / calendar-anchored).
 */
scheduledFor: string, doneAt: string | null, skipped: boolean | null, 
/**
 * Days added to the routine's projected goal-completion date when
 * this instance was missed.
 */
extensionContribution: number, failingPoints: number, successPoints: number, };

/**
 * One snapshot of project / lifetime success rate. The score engine
 * appends a daily snapshot so charts and rolling-30d numbers exist.
 */
export type ScoreSnapshot = { 
/**
 * ISO-8601 date the snapshot represents.
 */
date: string, successPoints: number, failingPoints: number, 
/**
 * success_points / (success_points + failing_points), or 1.0 if both 0.
 */
successRate: number, };

export type ScoreSummary = { lifetime: ScoreSnapshot, rolling30d: ScoreSnapshot, daily: Array<ScoreSnapshot>, };

export type Script = { id: string, name: string, cmd: string, desc: string | null, group: ScriptGroup, default: boolean | null, icon: string | null, env_defaults: Array<ScriptEnvVar>, };

export type ScriptEnvVar = { key: string, default: string, };

export type ScriptGroup = "run" | "build" | "check" | "util";

export type Session = { id: string, 
/**
 * Provider id (`"claude"` | `"codex"` | `"opencode"` | …).
 */
provider: string, projectPath: string, title: string, when: string, turns: number, duration: string, status: SessionStatus, last: string, model: string, branch: string | null, };

export type SessionStartResult = { 
/**
 * True when the headline notification just fired (first session of
 * the local day). False on subsequent calls within the same day.
 */
fired: boolean, 
/**
 * Local `YYYY-MM-DD` of the session start.
 */
localDate: string, 
/**
 * Snapshot of today right at session start, if the call fired.
 */
today: PlannerToday | null, };

export type SessionStatus = "active" | "idle" | "archived";

export type Settings = { general: GeneralSettings, editors: EditorsSettings, git: GitSettings, watchers: Array<WatchRoot>, templates: Array<Template>, shortcuts: { [key in string]?: string }, advanced: AdvancedSettings, 
/**
 * Multi-provider session config. `serde(default)` keeps older
 * `settings.json` files loadable without a migration step.
 */
providers: ProvidersSettings, };

export type SoonestMilestoneRef = { id: string, projectId: string, projectName: string, title: string, deadline: string, priority: Priority, daysLeft: number, };

export type SystemDiskUsage = { totalBytes: number, freeBytes: number, usedBytes: number, total: string, free: string, used: string, mountPoint: string, pctUsed: number, };

export type Template = { id: string, label: string, color: string, hint: string, path: string, builtin: boolean, };

export type Theme = "dark" | "light" | "system";

/**
 * Which projects appear in the cross-project timeline view. Curated by
 * the user via `TimelineProjectPicker`.
 */
export type TimelineConfig = { 
/**
 * User-pinned projects. Order matters (renders top-to-bottom).
 */
pinnedProjectIds: Array<string>, 
/**
 * Default visible range — `"week"` or `"month"`.
 */
visibleRange: string, };

export type TimelineData = { config: TimelineConfig, rows: Array<TimelineRow>, 
/**
 * Inclusive start of the visible window, `YYYY-MM-DD`.
 */
start: string, 
/**
 * Inclusive end of the visible window, `YYYY-MM-DD`.
 */
end: string, 
/**
 * Today in local time, `YYYY-MM-DD`.
 */
today: string, };

/**
 * One row in the timeline — a single pinned project with its
 * milestones and project-scoped routine instances clipped to the
 * visible window.
 */
export type TimelineRow = { projectId: string, projectName: string, 
/**
 * Hex color of the project — drives bar fill.
 */
projectColor: string, milestones: Array<Milestone>, routines: Array<Routine>, routineInstances: Array<RoutineInstance>, };

/**
 * One Today-view item. Discriminated on `kind` so the React side can
 * render todos / milestones / routine-instances with one component
 * list.
 */
export type TodayItem = { "kind": "todo", id: string, projectId: string, projectName: string, text: string, priority: Priority, deadline: string | null, score: number, daysOverdue: number, pinnedToday: boolean, } | { "kind": "milestone-deadline", id: string, projectId: string, projectName: string, title: string, deadline: string, priority: Priority, score: number, } | { "kind": "routine-instance", id: string, routineId: string, projectId: string | null, projectName: string | null, title: string, scheduledFor: string, priority: Priority, score: number, };

export type Todo = { id: string, done: boolean, text: string, 
/**
 * Legacy free-form due label (e.g. `"today"`, `"fri"`, ISO-8601).
 * Preserved for backward compatibility; new writes prefer `deadline`.
 */
due: string | null, createdAt: string, 
/**
 * Owning project id. Optional during migration window — populated by
 * the upsert path going forward.
 */
projectId: string | null, 
/**
 * Membership in a project milestone.
 */
milestoneId: string | null, 
/**
 * Set when this todo was generated by a routine instance.
 */
routineInstanceId: string | null, 
/**
 * Importance bucket. Defaults to P2 when absent.
 */
priority: Priority | null, 
/**
 * Structured ISO-8601 deadline. Replaces free-form `due` in new writes.
 */
deadline: string | null, 
/**
 * Estimated minutes-of-work (for the workload bar).
 */
estimate: bigint | null, 
/**
 * User explicitly pinned this todo into Today, overriding scoring.
 */
pinnedToday: boolean | null, 
/**
 * ISO-8601 completion timestamp (set when `done` flips to true).
 */
doneAt: string | null, };

export type WatchRoot = { path: string, depth: number, repoCount: number, };
